---
title: "Assignment 3 - Data 603"
output:
  html_document:
    df_print: paged
  pdf_document: default
date: "2024-12-08"
geometry: margin=1.2cm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(purrr)
library(leaps)
library(olsrr)
library(MASS)
Adult_mortality=read.csv("Life Expectancy Data.csv")
```

```{r echo=TRUE}
country_region_mapping=c(
  "Afghanistan" = "Asia",
  "Albania" = "Europe",
  "Algeria" = "Africa",
  "Angola" = "Africa",
  "Antigua and Barbuda" = "Caribbean",
  "Argentina" = "South America",
  "Armenia" = "Asia",
  "Australia" = "Oceania",
  "Austria" = "Europe",
  "Azerbaijan" = "Asia",
  "Bahamas" = "Caribbean",
  "Bahrain" = "Asia",
  "Bangladesh" = "Asia",
  "Barbados" = "Caribbean",
  "Belarus" = "Europe",
  "Belgium" = "Europe",
  "Belize" = "North America",
  "Benin" = "Africa",
  "Bhutan" = "Asia",
  "Bolivia (Plurinational State of)" = "South America",
  "Bosnia and Herzegovina" = "Europe",
  "Botswana" = "Africa",
  "Brazil" = "South America",
  "Brunei Darussalam" = "Asia",
  "Bulgaria" = "Europe",
  "Burkina Faso" = "Africa",
  "Burundi" = "Africa",
  "Côte d'Ivoire" = "Africa",
  "Cabo Verde" = "Africa",
  "Cambodia" = "Asia",
  "Cameroon" = "Africa",
  "Canada" = "North America",
  "Central African Republic" = "Africa",
  "Chad" = "Africa",
  "Chile" = "South America",
  "China" = "Asia",
  "Colombia" = "South America",
  "Comoros" = "Africa",
  "Congo" = "Africa",
  "Cook Islands" = "Oceania",
  "Costa Rica" = "North America",
  "Croatia" = "Europe",
  "Cuba" = "Caribbean",
  "Cyprus" = "Europe",
  "Czechia" = "Europe",
  "Democratic People's Republic of Korea" = "Asia",
  "Democratic Republic of the Congo" = "Africa",
  "Denmark" = "Europe",
  "Djibouti" = "Africa",
  "Dominica" = "Caribbean",
  "Dominican Republic" = "Caribbean",
  "Ecuador" = "South America",
  "Egypt" = "Africa",
  "El Salvador" = "North America",
  "Equatorial Guinea" = "Africa",
  "Eritrea" = "Africa",
  "Estonia" = "Europe",
  "Ethiopia" = "Africa",
  "Fiji" = "Oceania",
  "Finland" = "Europe",
  "France" = "Europe",
  "Gabon" = "Africa",
  "Gambia" = "Africa",
  "Georgia" = "Europe",
  "Germany" = "Europe",
  "Ghana" = "Africa",
  "Greece" = "Europe",
  "Grenada" = "Caribbean",
  "Guatemala" = "North America",
  "Guinea" = "Africa",
  "Guinea-Bissau" = "Africa",
  "Guyana" = "South America",
  "Haiti" = "Caribbean",
  "Honduras" = "North America",
  "Hungary" = "Europe",
  "Iceland" = "Europe",
  "India" = "Asia",
  "Indonesia" = "Asia",
  "Iran (Islamic Republic of)" = "Asia",
  "Iraq" = "Asia",
  "Ireland" = "Europe",
  "Israel" = "Asia",
  "Italy" = "Europe",
  "Jamaica" = "Caribbean",
  "Japan" = "Asia",
  "Jordan" = "Asia",
  "Kazakhstan" = "Asia",
  "Kenya" = "Africa",
  "Kiribati" = "Oceania",
  "Kuwait" = "Asia",
  "Kyrgyzstan" = "Asia",
  "Lao People's Democratic Republic" = "Asia",
  "Latvia" = "Europe",
  "Lebanon" = "Asia",
  "Lesotho" = "Africa",
  "Liberia" = "Africa",
  "Libya" = "Africa",
  "Lithuania" = "Europe",
  "Luxembourg" = "Europe",
  "Madagascar" = "Africa",
  "Malawi" = "Africa",
  "Malaysia" = "Asia",
  "Maldives" = "Asia",
  "Mali" = "Africa",
  "Malta" = "Europe",
  "Marshall Islands" = "Oceania",
  "Mauritania" = "Africa",
  "Mauritius" = "Africa",
  "Mexico" = "North America",
  "Micronesia (Federated States of)" = "Oceania",
  "Monaco" = "Europe",
  "Mongolia" = "Asia",
  "Montenegro" = "Europe",
  "Morocco" = "Africa",
  "Mozambique" = "Africa",
  "Myanmar" = "Asia",
  "Namibia" = "Africa",
  "Nauru" = "Oceania",
  "Nepal" = "Asia",
  "Netherlands" = "Europe",
  "New Zealand" = "Oceania",
  "Nicaragua" = "North America",
  "Niger" = "Africa",
  "Nigeria" = "Africa",
  "Niue" = "Oceania",
  "Norway" = "Europe",
  "Oman" = "Asia",
  "Pakistan" = "Asia",
  "Palau" = "Oceania",
  "Panama" = "North America",
  "Papua New Guinea" = "Oceania",
  "Paraguay" = "South America",
  "Peru" = "South America",
  "Philippines" = "Asia",
  "Poland" = "Europe",
  "Portugal" = "Europe",
  "Qatar" = "Asia",
  "Republic of Korea" = "Asia",
  "Republic of Moldova" = "Europe",
  "Romania" = "Europe",
  "Russian Federation" = "Europe",
  "Rwanda" = "Africa",
  "Saint Kitts and Nevis" = "Caribbean",
  "Saint Lucia" = "Caribbean",
  "Saint Vincent and the Grenadines" = "Caribbean",
  "Samoa" = "Oceania",
  "San Marino" = "Europe",
  "Sao Tome and Principe" = "Africa",
  "Saudi Arabia" = "Asia",
  "Senegal" = "Africa",
  "Serbia" = "Europe",
  "Seychelles" = "Africa",
  "Sierra Leone" = "Africa",
  "Singapore" = "Asia",
  "Slovakia" = "Europe",
  "Slovenia" = "Europe",
  "Solomon Islands" = "Oceania",
  "Somalia" = "Africa",
  "South Africa" = "Africa",
  "South Sudan" = "Africa",
  "Spain" = "Europe",
  "Sri Lanka" = "Asia",
  "Sudan" = "Africa",
  "Suriname" = "South America",
  "Swaziland" = "Africa",
  "Sweden" = "Europe",
  "Switzerland" = "Europe",
  "Syrian Arab Republic" = "Asia",
  "Tajikistan" = "Asia",
  "Thailand" = "Asia",
  "The former Yugoslav republic of Macedonia" = "Europe",
  "Timor-Leste" = "Asia",
  "Togo" = "Africa",
  "Tonga" = "Oceania",
  "Trinidad and Tobago" = "Caribbean",
  "Tunisia" = "Africa",
  "Turkey" = "Europe",
  "Turkmenistan" = "Asia",
  "Tuvalu" = "Oceania",
  "Uganda" = "Africa",
  "Ukraine" = "Europe",
  "United Arab Emirates" = "Asia",
  "United Kingdom of Great Britain and Northern Ireland" = "Europe",
  "United Republic of Tanzania" = "Africa",
  "United States of America" = "North America",
  "Uruguay" = "South America",
  "Uzbekistan" = "Asia",
  "Vanuatu" = "Oceania",
  "Venezuela (Bolivarian Republic of)" = "South America",
  "Viet Nam" = "Asia",
  "Yemen" = "Asia",
  "Zambia" = "Africa",
  "Zimbabwe" = "Africa"
)

new_data=Adult_mortality%>%
  mutate(region=country_region_mapping[as.character(Country)])
```

```{r echo=TRUE}
full_model_adult_mortality0=lm(Adult.Mortality~ ., data=new_data)
summary(full_model_adult_mortality0)
```
```{r echo=TRUE}
full_model_adult_mortality01=lm(Adult.Mortality~Country+HIV.AIDS, data=new_data)
summary(full_model_adult_mortality01)
```

```{r echo=TRUE}
full_model_adult_mortality=lm(Adult.Mortality~region+factor(Year)+Status+Life.expectancy+Alcohol+Hepatitis.B+Measles+Total.expenditure+percentage.expenditure+Diphtheria+HIV.AIDS+GDP+Population+Income.composition.of.resources+Schooling, data=new_data)
summary(full_model_adult_mortality)
```
  
```{r echo=TRUE}
Reduced_Model1=lm(Adult.Mortality~region+factor(Year)+Status+Life.expectancy+Alcohol+Hepatitis.B+Measles+Total.expenditure+Diphtheria+HIV.AIDS+GDP+Population+Income.composition.of.resources+Schooling, data=new_data)
summary(Reduced_Model1)
```
```{r echo=TRUE}
Reduced_Model2=lm(Adult.Mortality~factor(Year)+Status+Life.expectancy+Alcohol+Hepatitis.B+Measles+Total.expenditure+Diphtheria+HIV.AIDS+GDP+Population+Income.composition.of.resources+Schooling, data=new_data)
summary(Reduced_Model2)
```
```{r echo=TRUE}
Reduced_Model3=lm(Adult.Mortality~factor(Year)+Status+Life.expectancy+Alcohol+Hepatitis.B+Measles+Total.expenditure+Diphtheria+HIV.AIDS+GDP+Population+Schooling, data=new_data)
summary(Reduced_Model3)
```
```{r echo=TRUE}
Reduced_Model4=lm(Adult.Mortality~factor(Year)+Status+Life.expectancy+Alcohol+Hepatitis.B+Measles+Total.expenditure+Diphtheria+HIV.AIDS+GDP+Schooling, data=new_data)
summary(Reduced_Model4)
```

```{r echo=TRUE}
Reduced_Model5=lm(Adult.Mortality~factor(Year)+Status+Life.expectancy+Alcohol+Hepatitis.B+Measles+Total.expenditure+Diphtheria+HIV.AIDS+Schooling, data=new_data)
summary(Reduced_Model5)
```

```{r echo=TRUE}
Reduced_Model6=lm(Adult.Mortality~factor(Year)+Status+Life.expectancy+Alcohol+Measles+Total.expenditure+Diphtheria+HIV.AIDS+Schooling, data=new_data)
summary(Reduced_Model6)
```

```{r echo=TRUE}
Reduced_Model7=lm(Adult.Mortality~factor(Year)+Status+Life.expectancy+Alcohol+Measles+Total.expenditure+Diphtheria+HIV.AIDS, data=new_data)
summary(Reduced_Model7)
```

```{r echo=TRUE}
Reduced_Model8=lm(Adult.Mortality~Status+Life.expectancy+Alcohol+Measles+Total.expenditure+Diphtheria+HIV.AIDS, data=new_data)
summary(Reduced_Model8)
```
```{r echo=TRUE}
Reduced_Model9=lm(Adult.Mortality~Status+Life.expectancy+Alcohol+Measles+Diphtheria+HIV.AIDS, data=new_data)
summary(Reduced_Model9)
```

```{r echo=TRUE}
new_data2=Adult_mortality%>%
  mutate(region=country_region_mapping[as.character(Country)])

new_data2$Year[which(new_data2$Year==2001)]="2001"
new_data2$Year[which(new_data2$Year==2002)]="2002"
new_data2$Year[which(new_data2$Year==2003)]="2003"
new_data2$Year[which(new_data2$Year==2004)]="2004"
new_data2$Year[which(new_data2$Year==2005)]="2005"
new_data2$Year[which(new_data2$Year==2006)]="2006"
new_data2$Year[which(new_data2$Year==2007)]="2007"
new_data2$Year[which(new_data2$Year==2008)]="2008"
new_data2$Year[which(new_data2$Year==2009)]="2009"
new_data2$Year[which(new_data2$Year==2020)]="2010"
new_data2$Year[which(new_data2$Year==2011)]="2011"
new_data2$Year[which(new_data2$Year==2012)]="2012"
new_data2$Year[which(new_data2$Year==2013)]="2013"
new_data2$Year[which(new_data2$Year==2014)]="2014"
new_data2$Year[which(new_data2$Year==2015)]="2015"

full_model_adult_mortality2=lm(Adult.Mortality~region+Year+Status+Life.expectancy+Alcohol+Hepatitis.B+Measles+Total.expenditure+percentage.expenditure+Diphtheria+HIV.AIDS+GDP+Population+Income.composition.of.resources+Schooling, data=new_data2)
summary(full_model_adult_mortality2)

stepmod=ols_step_both_p(full_model_adult_mortality2,p_enter = 0.1, p_remove = 0.3, details=TRUE)
```

```{r echo=TRUE}
Model_step=lm(Adult.Mortality ~ Life.expectancy + HIV.AIDS + Alcohol + Measles + Schooling + Status, data=new_data2)
summary(Model_step)
```

```{r echo=TRUE}
stepmod1=ols_step_forward_p(full_model_adult_mortality2,p_val = 0.3, details=TRUE)
```

```{r echo=TRUE}
Model_step_forward=lm(Adult.Mortality ~ Life.expectancy + HIV.AIDS + Alcohol + Measles + Schooling + Status + Hepatitis.B, data=new_data2)
summary(Model_step_forward)
```

```{r echo=TRUE}
stepmod2=ols_step_backward_p(full_model_adult_mortality2, p_val = 0.3, details=TRUE)
```
```{r echo=TRUE}
Model_step_backward=lm(Adult.Mortality ~ Status + Life.expectancy + Alcohol + Hepatitis.B + Measles + HIV.AIDS + Schooling, data=new_data2)
summary(Model_step_backward)
```

```{r echo=TRUE}
full_model_adult_mortality3=lm(Adult.Mortality~ ., data=new_data2)
summary(full_model_adult_mortality3)
```

```{r echo=TRUE}
stepmod4=ols_step_both_p(full_model_adult_mortality3,p_enter = 0.1, p_remove = 0.3, details=TRUE)
```

```{r echo=TRUE}
stepmpd_Model=lm( Adult.Mortality ~ Life.expectancy + HIV.AIDS + infant.deaths + Schooling + Status + Country, data=new_data2)
summary(stepmpd_Model)
```

```{r echo=TRUE}
stepmod5=ols_step_forward_p(full_model_adult_mortality3,p_val = 0.3, details=TRUE)
```

```{r echo=TRUE}
stepmpd_Model2=lm(Adult.Mortality~Life.expectancy + HIV.AIDS + Alcohol + infant.deaths + Schooling + Status + Country + Income.composition.of.resources + Diphtheria, data=new_data2)
summary(stepmpd_Model2)
```

```{r echo=TRUE}
stepmod=ols_step_backward_p(full_model_adult_mortality3, p_val = 0.3, details=TRUE)
```
```{r echo=TRUE}
stepmpd_Model3=lm(Adult.Mortality~Country + Year + Status + Life.expectancy + infant.deaths + Diphtheria + HIV.AIDS + region, data=new_data2)
summary(stepmpd_Model3)
```

```{r echo=TRUE}
Voller_Test=function(data, Antwort, Vorhersage) {
  Bestes_Model_r2=NULL
  Bester_r2=-Inf
  Bestes_Model_RSE=NULL
  Bester_RSE=Inf
  Bestes_Model_ACI=NULL
  Bester_ACI=Inf
  Bestes_Formular_r2=NULL
  Bestes_Formular_RSE=NULL
  Bestes_Formular_ACI=NULL
  
  for (i in 1:length(Vorhersage)) {
    Kombinationen=combn(Vorhersage, i, simplify = FALSE)
    for (Kombi in Kombinationen) {
      Regeln=paste(Kombi, collapse = "+")
      Formular=paste(Antwort, "~", Regeln)
      Model=lm(as.formula(Formular), data=data)
      
      r2=summary(Model)$adj.r.squared
      RSE=sqrt(mean(residuals(Model)^2))
      AIC=AIC(Model)
      
      if (r2> Bester_r2) {
        Bester_r2=r2
        Bestes_Model_r2=Model
        Bestes_Formular_r2=Formular
      }
      if (RSE < Bester_RSE) {
        Bester_RSE=RSE
        Bestes_Model_RSE=Model
        Bestes_Formular_RSE=Formular
      }
      if (AIC < Bester_ACI) {
        Bester_ACI=AIC
        Bestes_Model_ACI=Model
        Bestes_Formular_ACI=Formular
      }
    }
  }
  
  return(list(Bestes_Model_r2=Bestes_Model_r2, Bestes_Formular_r2=Bestes_Formular_r2, Bester_r2=Bester_r2,
              Bestes_Model_RSE=Bestes_Model_RSE, Bestes_Formular_RSE=Bestes_Formular_RSE, Bester_RSE=Bester_RSE,
              Bestes_Model_ACI=Bestes_Model_ACI, Bestes_Formular_ACI=Bestes_Formular_ACI, Bester_ACI=Bester_ACI))
}

Antwort="Adult.Mortality"
Vorhersage=c("region","factor(Year)","Status","Life.expectancy","Alcohol","Hepatitis.B","Measles","Total.expenditure","percentage.expenditure","Diphtheria","HIV.AIDS","GDP","Population","Income.composition.of.resources","Schooling")

Resultate=Voller_Test(new_data, Antwort, Vorhersage)
```

```{r echo=TRUE}
cat("Best Formula for Adjusted R-squared:", Resultate$Bestes_Formular_r2, "\n")
cat("Best Adjusted R-squared:", Resultate$Bester_r2, "\n")
cat("Best Formula for RSE:", Resultate$Bestes_Formular_RSE, "\n")
cat("Best RSE:", Resultate$Bester_RSE, "\n")
cat("Best Formula for AIC:", Resultate$Bestes_Formular_ACI, "\n")
cat("Best AIC:", Resultate$Bester_ACI, "\n")
```

```{r echo=TRUE}
Highest_r2=lm(Adult.Mortality ~ factor(Year)+Status+Life.expectancy+Alcohol+Hepatitis.B+Measles+HIV.AIDS, data=new_data)
summary(Highest_r2)
Lowest_RSE=lm(Adult.Mortality ~ region+factor(Year)+Status+Life.expectancy+Hepatitis.B+Measles+percentage.expenditure, data=new_data)
summary(Lowest_RSE)
Lowest_ACI=lm(Adult.Mortality ~ Status+Life.expectancy+Alcohol+Hepatitis.B+Measles+HIV.AIDS+GDP+Population+Schooling, data=new_data)
summary(Lowest_ACI)
```

```{r echo=TRUE}
Adult_Mortality_Subsets=ols_step_best_subset(full_model_adult_mortality2, details=TRUE)
Adult_Mortality_Subsets$metrics
#Third is the best
```

Life.expectancy+HIV.AIDS+Alcohol+Status+ Measles+ Schooling are the most common varaibles
Schooling and Hepatitis B occurs three times
Diphtheria and factor(Year) occurs once

```{r echo=TRUE}
Interaction_Model=lm(Adult.Mortality ~(Life.expectancy+HIV.AIDS+Alcohol+Status+ Measles+ Schooling+Hepatitis.B+Diphtheria+factor(Year))^2, data= new_data)
summary(Interaction_Model)
```
```{r echo=TRUE}
Interaction_Model=lm(Adult.Mortality ~(Life.expectancy+HIV.AIDS+Alcohol+Status+ Measles+ Schooling+Hepatitis.B+Diphtheria+factor(Year))^2, data= new_data2)
summary(Interaction_Model)
```

```{r echo=TRUE}
Interaction_Model1=lm(Adult.Mortality~Life.expectancy+HIV.AIDS+Status+Diphtheria+Hepatitis.B+Alcohol+factor(Year)+Schooling+Measles+Life.expectancy*HIV.AIDS+Life.expectancy*Status+Life.expectancy*Diphtheria+Life.expectancy*Hepatitis.B+HIV.AIDS*Alcohol+HIV.AIDS*factor(Year)+HIV.AIDS*Schooling+Alcohol*Status+Alcohol*Measles+Measles*Hepatitis.B+Measles*factor(Year), data= new_data)
summary(Interaction_Model1)
```

```{r echo=TRUE}
Interaction_Model2=lm(Adult.Mortality~Life.expectancy+HIV.AIDS+Status+Diphtheria+Hepatitis.B+Alcohol+factor(Year)+Schooling+Measles+Life.expectancy*HIV.AIDS+Life.expectancy*Status+Life.expectancy*Diphtheria+Life.expectancy*Hepatitis.B+HIV.AIDS*Alcohol++HIV.AIDS*Schooling+Alcohol*Status+Alcohol*Measles+Measles*Hepatitis.B, data= new_data)
summary(Interaction_Model2)
```

```{r echo=TRUE}
Interaction_Model3=lm(Adult.Mortality~Life.expectancy+HIV.AIDS+Status+Diphtheria+Hepatitis.B+Alcohol+factor(Year)+Schooling+Measles+Life.expectancy*HIV.AIDS+Life.expectancy*Status+Life.expectancy*Diphtheria+Life.expectancy*Hepatitis.B+HIV.AIDS*Alcohol++HIV.AIDS*Schooling+Alcohol*Status+Measles*Hepatitis.B, data= new_data)
summary(Interaction_Model3)
```

```{r echo=TRUE}
Interaction_Model4=lm(Adult.Mortality~Life.expectancy+HIV.AIDS+Status+Diphtheria+Hepatitis.B+Alcohol+factor(Year)+Schooling+Measles+Life.expectancy*Status+Life.expectancy*Diphtheria+Life.expectancy*Hepatitis.B+HIV.AIDS*Alcohol++HIV.AIDS*Schooling+Alcohol*Status+Measles*Hepatitis.B, data= new_data)
summary(Interaction_Model4)
```
```{r echo=TRUE}
Interaction_Model5=lm(Adult.Mortality~Life.expectancy+HIV.AIDS+Status+Diphtheria+Hepatitis.B+Alcohol+factor(Year)+Schooling+Measles+Life.expectancy*Status+Life.expectancy*Diphtheria+HIV.AIDS*Alcohol++HIV.AIDS*Schooling+Alcohol*Status+Measles*Hepatitis.B, data= new_data)
summary(Interaction_Model5)
```

```{r echo=TRUE}
Interaction_Model5=lm(Adult.Mortality~Life.expectancy+HIV.AIDS+Status+Diphtheria+Hepatitis.B+Alcohol+Schooling+Measles+Life.expectancy*Status+Life.expectancy*Diphtheria+HIV.AIDS*Alcohol++HIV.AIDS*Schooling+Alcohol*Status+Measles*Hepatitis.B, data= new_data)
summary(Interaction_Model5)
```

```{r echo=TRUE}
Voller_Test=function(data, Antwort, Vorhersage) {
  Bestes_Model_r2=NULL
  Bester_r2=-Inf
  Bestes_Model_RSE=NULL
  Bester_RSE=Inf
  Bestes_Model_ACI=NULL
  Bester_ACI=Inf
  Bestes_Formular_r2=NULL
  Bestes_Formular_RSE=NULL
  Bestes_Formular_ACI=NULL
  
  for (i in 1:length(Vorhersage)) {
    Kombinationen=combn(Vorhersage, i, simplify = FALSE)
    for (Kombi in Kombinationen) {
      Regeln=paste(Kombi, collapse = "+")
      Formular=paste(Antwort, "~", Regeln, "+ (", Regeln, ")^2")
      Model=lm(as.formula(Formular), data=data)
      
      r2=summary(Model)$adj.r.squared
      RSE=sqrt(mean(residuals(Model)^2))
      AIC=AIC(Model)
      
      if (r2> Bester_r2) {
        Bester_r2=r2
        Bestes_Model_r2=Model
        Bestes_Formular_r2=Formular
      }
      if (RSE < Bester_RSE) {
        Bester_RSE=RSE
        Bestes_Model_RSE=Model
        Bestes_Formular_RSE=Formular
      }
      if (AIC < Bester_ACI) {
        Bester_ACI=AIC
        Bestes_Model_ACI=Model
        Bestes_Formular_ACI=Formular
      }
    }
  }
  
  return(list(Bestes_Model_r2=Bestes_Model_r2, Bestes_Formular_r2=Bestes_Formular_r2, Bester_r2=Bester_r2,
              Bestes_Model_RSE=Bestes_Model_RSE, Bestes_Formular_RSE=Bestes_Formular_RSE, Bester_RSE=Bester_RSE,
              Bestes_Model_ACI=Bestes_Model_ACI, Bestes_Formular_ACI=Bestes_Formular_ACI, Bester_ACI=Bester_ACI))
}

Antwort="Adult.Mortality"
Vorhersage=c("Life.expectancy","HIV.AIDS","Alcohol","Status","Measles","Schooling","Hepatitis.B","Diphtheria","factor(Year)")

Resultate=Voller_Test(new_data, Antwort, Vorhersage)
```

```{r echo=TRUE}
cat("Best Formula for Adjusted R-squared:", Resultate$Bestes_Formular_r2, "\n")
cat("Best Adjusted R-squared:", Resultate$Bester_r2, "\n")
cat("Best Formula for RSE:", Resultate$Bestes_Formular_RSE, "\n")
cat("Best RSE:", Resultate$Bester_RSE, "\n")
cat("Best Formula for AIC:", Resultate$Bestes_Formular_ACI, "\n")
cat("Best AIC:", Resultate$Bester_ACI, "\n")
```

```{r echo=TRUE}
Best_adjusted_r2_model=lm(Adult.Mortality~Life.expectancy+HIV.AIDS+Alcohol+Status+Measles+Schooling+Hepatitis.B+Diphtheria+factor(Year) + ( Life.expectancy+HIV.AIDS+Alcohol+Status+Measles+Schooling+Hepatitis.B+Diphtheria+factor(Year) )^2, data=new_data)
summary(Best_adjusted_r2_model)
Best_RSE_model=lm(Adult.Mortality~ Life.expectancy+HIV.AIDS+Alcohol+Status+Measles+Schooling+Hepatitis.B+Diphtheria+factor(Year) + ( Life.expectancy+HIV.AIDS+Alcohol+Status+Measles+Schooling+Hepatitis.B+Diphtheria+factor(Year) )^2 ,data=new_data)
summary(Best_RSE_model)
Best_ACI_model=lm(Adult.Mortality~ Life.expectancy+HIV.AIDS+Alcohol+Status+Measles+Schooling+Hepatitis.B + ( Life.expectancy+HIV.AIDS+Alcohol+Status+Measles+Schooling+Hepatitis.B )^2 ,data=new_data)
summary(Best_ACI_model)
```
```{r echo=TRUE}
ggplot(Interaction_Model5, aes(x=.fitted, y=.resid)) +
  geom_point(colour = "purple") +
  geom_hline(yintercept = 0) +
  geom_smooth(colour = "green4")+
  ggtitle("Residual plot: Residual vs Fitted values") 
```

```{r echo=TRUE}
ggplot(Interaction_Model5, aes(x=.fitted, y=sqrt(abs(.stdresid)))) +
  geom_point(colour = "purple") +
  geom_hline(yintercept = 0) +
  geom_smooth( colour = "green4")+
   ggtitle("Scale-Location plot : Standardized Residual vs Fitted values") 
```
```{r echo=TRUE}
library(lmtest)
bptest(Interaction_Model5)
```

```{r echo=TRUE}
residuals=Interaction_Model5$residuals
length(residuals)
new_residuals=data.frame(residuals = residuals)
ggplot(new_residuals, aes(sample=residuals)) +
  stat_qq() +
  stat_qq_line()
```

```{r echo=TRUE}
ggplot(data = new_residuals, aes(x = residuals)) + 
  geom_histogram(breaks = seq(-90, 90, by = 5), col = "green3", fill = "green4") + 
  labs(title = "Histogram for residuals", x = "residuals", y = "Count")
```

```{r echo=TRUE}
shapiro.test(residuals(Interaction_Model5))
```

```{r echo=TRUE}
library(mctest)
#pairs(~Life.expectancy+HIV.AIDS+Status+Diphtheria+Hepatitis.B+Alcohol+Schooling+Measles, data=new_data)
```

```{r echo=TRUE}
imcdiag(Interaction_Model5, method="VIF")
```

```{r echo=TRUE}
plot(Interaction_Model5,which=5)
new_data[cooks.distance(Interaction_Model5)>0.5,]
plot(Interaction_Model5,pch=18,col="red",which=c(4))
lev=hatvalues(Interaction_Model5)
p = length(coef(Interaction_Model5))
n = nrow(new_data)
outlier2p = lev[lev>(2*p/n)]
outlier3p = lev[lev>(3*p/n)]
print("h_I>2p/n, outliers are")
print(outlier2p)
print("h_I>3p/n, outliers are")
print(outlier3p)
plot(rownames(new_data),lev, main = "Leverage in Advertising Dataset", xlab="observation",
    ylab = "Leverage Value")
abline(h = 2 *p/n, lty = 1)
abline(h = 3 *p/n, lty = 1)
```
